// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package repository

import (
	"database/sql"
	"time"

	"github.com/jackc/pgtype"
)

type Customer struct {
	ID        int64
	Name      string
	Phone     string
	Address   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Product struct {
	ID          int64
	Name        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CategoryID  int64
}

type ProductCategory struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	ParentID  sql.NullInt64
}

type PurchaseOrder struct {
	ID                 int64
	CreatedAt          time.Time
	UpdatedAt          time.Time
	SupplierID         int64
	AdditionalDiscount pgtype.Numeric
}

type PurchaseOrderItem struct {
	ID              int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
	PurchaseOrderID int64
	ProductID       int64
	Quantity        int32
	Amount          pgtype.Numeric
	Discount        pgtype.Numeric
}

type SaleOrder struct {
	ID                 int64
	CreatedAt          time.Time
	UpdatedAt          time.Time
	CustomerID         int64
	AdditionalDiscount pgtype.Numeric
}

type SaleOrderItem struct {
	ID          int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	SaleOrderID int64
	ProductID   int64
	Quantity    int32
	Amount      pgtype.Numeric
	Discount    pgtype.Numeric
}

type Supplier struct {
	ID        int64
	Name      string
	Phone     string
	Address   string
	CreatedAt time.Time
	UpdatedAt time.Time
}
