// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"database/sql"
)

type Product struct {
	ID          int64
	Name        string
	Description string
	CategoryID  int64
}

type ProductCategory struct {
	ID       int64
	Name     string
	ParentID sql.NullInt64
}
