// Code generated by sqlc. DO NOT EDIT.
// source: queries.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/jackc/pgconn"
)

const createProduct = `-- name: CreateProduct :execresult
INSERT INTO products (name, category)
VALUES ($1, $2)
`

type CreateProductParams struct {
	Name     string
	Category sql.NullString
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, createProduct, arg.Name, arg.Category)
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE
FROM products
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, category
FROM products
WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(&i.ID, &i.Name, &i.Category)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, category
FROM products
ORDER BY name
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(&i.ID, &i.Name, &i.Category); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
